-- general vim
vim.cmd("set expandtab")
vim.cmd("set tabstop=4")
vim.cmd("set softtabstop=4")
vim.cmd("set shiftwidth=4")
vim.cmd("set nu")
vim.cmd("set nowrap")
vim.cmd("set textwidth=80")
vim.cmd("set nrformats=")
vim.cmd("set ignorecase")
vim.cmd("set smartcase")
vim.keymap.set("n", "<C-w>h", "<Leader>h")
vim.keymap.set("n", "<C-w>l", "<Leader>l")
vim.keymap.set("n", "<C-w>j", "<Leader>j")
vim.keymap.set("n", "<C-w>k", "<Leader>k")
vim.g.mapleader = " "
